Feature/standbyplan
hannesbraun/badenair pull request #67
Opened 2020-04-11 13:23 UTC by nstuder

closes #53, closes #54 

Ich hoffe mal das das mit Spring so einigermaßen passt....

2020-04-11 19:06 UTC, jstuerzel requested changes
Ich würde den Zugriff auf das Repository in einen Service auslagern, da wir ja später noch weitere Logik wie das Erstellen des Plans benötigen. 
Der Test testet keine Funktionalität brauchen wir den dann überhaupt ?

2020-04-11 19:06 UTC, jstuerzel commented on server/src/main/java/de/hso/badenair/controller/PlanController.java
> +    private StandbyScheduleRepository standbyScheduleRepository;
```suggestion
@RequiredArgsConstructor
public class PlanController {

    private final StandbyScheduleRepository standbyScheduleRepository;

```
Field Injection sollte vermieden werden

2020-04-12 09:32 UTC, nstuder commented on server/src/main/java/de/hso/badenair/controller/PlanController.java
> +    private StandbyScheduleRepository standbyScheduleRepository;
Done

2020-04-12 10:36 UTC, jstuerzel approved these changes

2020-04-12 10:58 UTC, merged