Feature/ba 17.15
hannesbraun/badenair pull request #91
Opened 2020-04-24 11:04 UTC by julia-merettig

CheckIn funktioniert

2020-04-24 11:46 UTC, nstuder commented
Nächstes mal Base Branch auf Develop setzen und Reviewer hinzufügen ; )

2020-04-24 13:35 UTC, jstuerzel requested changes

2020-04-24 13:35 UTC, jstuerzel commented on server/src/main/java/de/hso/badenair/service/traveler/TravelerRepository.java
> +
```suggestion
@Repository
```
`@Repository` fehlt hier noch

2020-04-24 13:35 UTC, jstuerzel commented on server/src/main/java/de/hso/badenair/service/traveler/TravelerService.java
> +    }
Die Methode wird nicht verwendet kann also weg

2020-05-03 18:18 UTC, hannesbraun commented
Ich bin mir nicht ganz sicher, aber wird hier bedacht, dass zu einem Zeitpunkt bereits ein Check-In mit nicht allen Passagieren stattgefunden haben kann? In dem Fall dürften die in der Liste dann nur die Passagiere auftauchen, bei denen der Check-In noch nicht durchgeführt wurde. Ich habe sowas in der Art schon bei den gebuchten Flügen (#108 und #109) gemacht. Wenn alle Passagiere den Check-In schon gemacht haben, dann wird der Check-In Button dort gar nicht angezeigt.

Vielleicht übersehe ich auch nur was. Aber ansonsten sollte das noch geändert werden, denn  meiner Ansicht nach sollte es eigentlich nicht möglich sein, dass man einen Check-In zweimal durchführen kann.

2020-05-10 11:38 UTC, julia-merettig commented on server/src/main/java/de/hso/badenair/service/traveler/TravelerService.java
> +    }
Hab's entfernt

2020-05-10 11:42 UTC, julia-merettig commented on server/src/main/java/de/hso/badenair/service/traveler/TravelerRepository.java
> +
Hab ich das am richtigen Ort hinzugefügt? Bzw. stimmt das?
...
import org.springframework.stereotype.Repository;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Repository
@Service
@RequiredArgsConstructor
public class TravelerService { ...

2020-05-10 12:21 UTC, jstuerzel approved these changes

2020-05-11 12:50 UTC, merged